name: Deploy to Heroku

on:
  push:
    paths:
      - "backend/**"
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{secrets.HEROKU_MAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          dockerfile_directory: ../backend/
          process_type: web
