name: Deploy to Netlify

on:
  push:
    paths:
      - "frontend/**"
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm install
      - run: npm run build --if-present

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: "./frontend/build"
          deploy-message: "Deploy from Github Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
